package com.buildSteps.BuildStepsPro.navigation

object Routes {
    const val SPLASH         = "splash"
    const val WELCOME        = "welcome"
    const val ONBOARDING     = "onboarding"
    const val DASHBOARD      = "dashboard"
    const val PROJECTS       = "projects"
    const val ADD_PROJECT    = "add_project"
    const val ZONES          = "zones/{projectId}"
    const val ADD_ZONE       = "add_zone/{projectId}"
    const val TASKS          = "tasks/{projectId}"
    const val ADD_TASK       = "add_task/{projectId}/{zoneId}"
    const val TASK_CATEGORIES = "task_categories"
    const val DEPENDENCIES   = "dependencies/{projectId}"
    const val DEP_GRAPH      = "dep_graph/{projectId}"
    const val TIMELINE       = "timeline/{projectId}"
    const val AUTO_PLAN      = "auto_plan/{projectId}"
    const val ERRORS         = "errors/{projectId}"
    const val FIX_SUGGESTIONS = "fix_suggestions/{projectId}"
    const val MATERIALS      = "materials/{projectId}"
    const val ADD_MATERIAL   = "add_material/{projectId}"
    const val BUDGET         = "budget/{projectId}"
    const val COST_PER_TASK  = "cost_per_task/{projectId}"
    const val PROGRESS       = "progress/{projectId}"
    const val TASKS_BOARD    = "tasks_board/{projectId}"
    const val CALENDAR       = "calendar/{projectId}"
    const val REPORTS        = "reports/{projectId}"
    const val ACTIVITY       = "activity/{projectId}"
    const val NOTIFICATIONS  = "notifications"
    const val PROFILE        = "profile"
    const val SETTINGS       = "settings"

    fun zones(pid: String)        = "zones/$pid"
    fun addZone(pid: String)      = "add_zone/$pid"
    fun tasks(pid: String)        = "tasks/$pid"
    fun addTask(pid: String, zid: String = "none") = "add_task/$pid/$zid"
    fun deps(pid: String)         = "dependencies/$pid"
    fun depGraph(pid: String)     = "dep_graph/$pid"
    fun timeline(pid: String)     = "timeline/$pid"
    fun autoPlan(pid: String)     = "auto_plan/$pid"
    fun errors(pid: String)       = "errors/$pid"
    fun fixSuggestions(pid: String) = "fix_suggestions/$pid"
    fun materials(pid: String)    = "materials/$pid"
    fun addMaterial(pid: String)  = "add_material/$pid"
    fun budget(pid: String)       = "budget/$pid"
    fun costPerTask(pid: String)  = "cost_per_task/$pid"
    fun progress(pid: String)     = "progress/$pid"
    fun tasksBoard(pid: String)   = "tasks_board/$pid"
    fun calendar(pid: String)     = "calendar/$pid"
    fun reports(pid: String)      = "reports/$pid"
    fun activity(pid: String)     = "activity/$pid"
}
